let hello = "hello";
hello = "hello_1";
let owu = "owu";
owu = "owu_1";
let ua = "ua";
ua = "ua_1";
let one = 1;
one = 10;
let ten = 10;
ten = 100;
let a_999 = -999;
a_999 = 999;
let a_123 = 123;
a_123 = -123;
const P = 3.14;
const e = 2.7;
let a_16 = 16;
a_16 = 160;
let boolTrue = true;
boolTrue = false;
let boolFalse = false;
boolFalse = true;
console.log(hello);
console.log(owu);
console.log(ua);
console.log(one);
console.log(ten);
console.log(a_999);
console.log(a_123);
console.log(P);
console.log(e);
console.log(a_16);
console.log(boolTrue);
console.log(boolFalse);
alert(hello);
alert(owu);
alert(ua);
alert(one);
alert(ten);
alert(a_999);
alert(a_123);
alert(P);
alert(e);
alert(a_16);
alert(boolTrue);
alert(boolFalse);
document.write(hello + '<br>');
document.write(owu + '<br>');
document.write(ua + '<br>');
document.write(one + '<br>');
document.write(ten + '<br>');
document.write(a_999 + '<br>');
document.write(a_123 + '<br>');
document.write(P + '<br>');
document.write(e + '<br>');
document.write(a_16 + '<br>');
document.write(boolTrue + '<br>');
document.write(boolFalse + '<br>');